Add automatic style checks.
jitsi/jitsi-srtp pull request #24
Opened 2020-09-16 15:00 UTC by JonathanLennox

2020-09-16 15:10 UTC, ibauersachs requested changes

2020-09-16 15:10 UTC, ibauersachs commented on .github/workflows/maven.yml
> +        java-version: 1.8
Can we please do a matrix build with Java 8 and 11? See #15 for an example

2020-09-16 15:10 UTC, ibauersachs commented on pom.xml
> +	    <plugin>
Weird indents...

2020-09-16 15:27 UTC, ibauersachs submitted a review, later dismissed
If you push your branch to this repo we'll see if they actually succeed. I'm not too familiar with the cache action, but I think it's necessary to include the Matrix parameters (i.e. the Java version) to the cache key.

2020-09-16 17:03 UTC, JonathanLennox commented
> If you push your branch to this repo we'll see if they actually succeed. I'm not too familiar with the cache action, but I think it's necessary to include the Matrix parameters (i.e. the Java version) to the cache key.

I've copied the version from jitsi-utils instead.

2020-09-16 20:49 UTC, ibauersachs approved these changes

2020-09-16 22:39 UTC, JonathanLennox commented
@ibauersachs Can you re-approve?

2020-09-17 05:34 UTC, ibauersachs approved these changes

2020-09-17 14:10 UTC, merged